# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: KPR & Associates
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here.
  We service small businesses with cloud-based financial reporting and
  tax preparation.
copyright: 'Copyright &copy; 2020 KPR & Associates. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com
  - title: instagram
    url: https://www.instagram.com/renoobie/
  - title: linkedin
    url: https://www.linkedin.com
